order += "battery 1"
battery 1 {
        format = "⚡%consumption %status%percentage %remaining"
        format_down = "No battery"
        status_chr = "🔌"
        status_bat = "🔋"
        status_unk = "?"
        status_full = "☻"
        path = "/sys/class/power_supply/BAT%d/uevent"
	last_full_capacity = true
        low_threshold = 10
}

order += "disk /"
disk "/" {
        format = "💾%used"
}

order += "disk /var/lib/docker"
disk "/var/lib/docker" {
        format = "🐋%used"
}

order += "memory"
memory {
        format = "🐏%percentage_used %used"
        threshold_degraded = "10%"
        format_degraded = "🐏LOW %percentage_free %free"
}

order += "cpu_temperature 0"
cpu_temperature 0 {
        format = "🔥%degrees°C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon5/temp1_input"
}

order += "cpu_usage"
cpu_usage {
        format = "👺%usage"
        format_above_threshold = "👺%usage"
}

order += "load"
load {
	format = "🥜%1min %5min %15min"
	format_above_threshold = "🥜%1min %5min %15min"
}

order += "tztime local"
tztime local {
        format = "⏲%Y-%m-%d %H:%M:%S"
}

order += "volume master"
volume master {
        format = "🔉%volume"
        format_muted = "🔇%volume"
        device = "pulse"
}

order += "wireless wlan0"
wireless wlan0 {
        format_quality = "%d%s"
        format_up = "🛰️%quality"
        format_down = "🛰️down"
}
