# Set the prefix
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# Remap copy-mode
unbind C-[
bind-key C-q copy-mode

# Speed up delay between commands
set -sg escape-time 0

# Move between window
bind-key -n M-j previous-window
bind-key -n M-k next-window
bind-key -n M-J swap-window -t -1\; select-window -t -1
bind-key -n M-K swap-window -t +1\; select-window -t +1

# Move between session
bind-key -n C-M-j switch-client -p
bind-key -n C-M-k switch-client -n

# Resize splits
bind-key -n C-M-Down resize-pane -D 5
bind-key -n C-M-Up resize-pane -U 5
bind-key -n C-M-Left resize-pane -L 5
bind-key -n C-M-Right resize-pane -R 5

# New named window
bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# Quick ssh
bind-key S command-prompt -p "SSH Host: " "new-window -n '%1' ssh '%1'"

bind-key C-s display-menu -T SSH \
  bst "" "new-window -n bastion ssh bastion1" \
  frt 1 "new-window -n frt ssh frt" \
  db1 2 "new-window -n db1 ssh db1" \
  ast 3 "new-window -n ast ssh ast" \
  php2 4 "new-window -n php2 ssh php2" \
  "" \
  cr1-de "" "new-window -n cr1-de ssh cr1-de" \
  cr1-nl "" "new-window -n cr1-nl ssh cr1-nl" \
  h1-de "" "new-window -n h1-de ssh h1-de"