set -g status-interval 1

set -g status-bg "#0c1530"
set -g status-fg "#2c375a"

set -g status-right-length 150
set -g status-left-length 150

set -g status-left '#[fg=#d8b5e3, bg=#1a2546] #(ip -4 -o a show dev wlan0 | cut -d\  -f7) #[fg=#1a2546, bg=#303070]'
set -ga status-left '#[fg=#d8b5e3, bg=#303070] 🥜#(cat /proc/loadavg | cut -d\  -f-3) #[fg=#303070, bg=#0c1530] '

set -g window-status-format ' #[fg=#2c375a, bg=#black]#I: #W '

set -g window-status-current-format '#[fg=#0c1530, bg=black]#[fg=#d8b5e3, bg=black] #I: #W #[fg=#0c1530, bg=black]'

set -g status-right "#[fg=#1a2546, bg=#0c1530]#[fg=#d8b5e3, bg=#1a2546] 🔥#(sensors -j acpitz-acpi-0 | jq '.\"acpitz-acpi-0\".temp1.temp1_input')°C "
set -ga status-right '#[fg=#0c1530, bg=#1a2546]#[fg=#d8b5e3, bg=#0c1530] 🎶#(playerctl metadata --format "{{ trunc(title,20) }} - {{ trunc(artist,15) }}") ' 
